stages:
  - buildn
  - deploy

build:
  image: node:16-alpine
  stage: build
  script:
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    paths:
      - build/

pages:
  image: node:16-alpine
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv build public
  artifacts:
    paths:
      - public # https://pedro_m_santos.gitlab.io/glenn/index.html
