stages:
  - build
  - deploy

build:
  image: node:16-alpine
  stage: build
  script:
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    paths:
      - build/

deploy to gitlab:
  image: node:16-alpine
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv build public
  artifacts:
    paths:
      - public # https://pedro_m_santos.gitlab.io/glenn/index.html

.deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws -- version
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete

